export const countryData = {
    AED: { country: "United Arab Emirates", name: "Dirham", flag: "AE" },
    AFN: { country: "Afghanistan", name: "Afghani", flag: "AF" },
    ALL: { country: "Albania", name: "Lek", flag: "AL" },
    AMD: { country: "Armenia", name: "Dram", flag: "AM" },
    ANG: { country: "Netherlands Antilles", name: "Guilder", flag: "AN" },
    AOA: { country: "Angola", name: "Kwanza", flag: "AO" },
    ARS: { country: "Argentina", name: "Peso", flag: "AR" },
    AUD: { country: "Australia", name: "Dollar", flag: "AU" },
    AWG: { country: "Aruba", name: "Florin", flag: "AW" },
    AZN: { country: "Azerbaijan", name: "Manat", flag: "AZ" },
    BAM: { country: "Bosnia-Herzegovina", name: "Convertible Mark", flag: "BA" },
    BBD: { country: "Barbados", name: "Dollar", flag: "BB" },
    BDT: { country: "Bangladesh", name: "Taka", flag: "BD" },
    BGN: { country: "Bulgaria", name: "Lev", flag: "BG" },
    BHD: { country: "Bahrain", name: "Dinar", flag: "BH" },
    BIF: { country: "Burundi", name: "Franc", flag: "BI" },
    BMD: { country: "Bermuda", name: "Dollar", flag: "BM" },
    BND: { country: "Brunei", name: "Dollar", flag: "BN" },
    BOB: { country: "Bolivia", name: "Boliviano", flag: "BO" },
    BRL: { country: "Brazil", name: "Real", flag: "BR" },
    BSD: { country: "Bahamas", name: "Dollar", flag: "BS" },
    BTN: { country: "Bhutan", name: "Ngultrum", flag: "BT" },
    BWP: { country: "Botswana", name: "Pula", flag: "BW" },
    BYN: { country: "Belarus", name: "Ruble", flag: "BY" },
    BZD: { country: "Belize", name: "Dollar", flag: "BZ" },
    CAD: { country: "Canada", name: "Dollar", flag: "CA" },
    CDF: { country: "Congo", name: "Franc", flag: "CD" },
    CHF: { country: "Switzerland", name: "Franc", flag: "CH" },
    CLP: { country: "Chile", name: "Peso", flag: "CL" },
    CNY: { country: "China", name: "Yuan", flag: "CN" },
    COP: { country: "Colombia", name: "Peso", flag: "CO" },
    CRC: { country: "Costa Rica", name: "Colon", flag: "CR" },
    CUP: { country: "Cuba", name: "Peso", flag: "CU" },
    CVE: { country: "Cape Verde", name: "Escudo", flag: "CV" },
    CZK: { country: "Czech Republic", name: "Koruna", flag: "CZ" },
    DJF: { country: "Djibouti", name: "Franc", flag: "DJ" },
    DKK: { country: "Denmark", name: "Krone", flag: "DK" },
    DOP: { country: "Dominican Republic", name: "Peso", flag: "DO" },
    DZD: { country: "Algeria", name: "Dinar", flag: "DZ" },
    EGP: { country: "Egypt", name: "Pound", flag: "EG" },
    ERN: { country: "Eritrea", name: "Nakfa", flag: "ER" },
    ETB: { country: "Ethiopia", name: "Birr", flag: "ET" },
    EUR: { country: "European Union", name: "Euro", flag: "EU" },
    FJD: { country: "Fiji", name: "Dollar", flag: "FJ" },
    GBP: { country: "United Kingdom", name: "Pound", flag: "GB" },
    GEL: { country: "Georgia", name: "Lari", flag: "GE" },
    GHS: { country: "Ghana", name: "Cedi", flag: "GH" },
    GIP: { country: "Gibraltar", name: "Pound", flag: "GI" },
    GMD: { country: "Gambia", name: "Dalasi", flag: "GM" },
    GNF: { country: "Guinea", name: "Franc", flag: "GN" },
    GTQ: { country: "Guatemala", name: "Quetzal", flag: "GT" },
    GYD: { country: "Guyana", name: "Dollar", flag: "GY" },
    HKD: { country: "Hong Kong", name: "Dollar", flag: "HK" },
    HNL: { country: "Honduras", name: "Lempira", flag: "HN" },
    HRK: { country: "Croatia", name: "Kuna", flag: "HR" },
    HTG: { country: "Haiti", name: "Gourde", flag: "HT" },
    HUF: { country: "Hungary", name: "Forint", flag: "HU" },
    IDR: { country: "Indonesia", name: "Rupiah", flag: "ID" },
    ILS: { country: "Israel", name: "Shekel", flag: "IL" },
    INR: { country: "India", name: "Rupee", flag: "IN" },
    IQD: { country: "Iraq", name: "Dinar", flag: "IQ" },
    IRR: { country: "Iran", name: "Rial", flag: "IR" },
    ISK: { country: "Iceland", name: "Krona", flag: "IS" },
    JMD: { country: "Jamaica", name: "Dollar", flag: "JM" },
    JOD: { country: "Jordan", name: "Dinar", flag: "JO" },
    JPY: { country: "Japan", name: "Yen", flag: "JP" },
    KES: { country: "Kenya", name: "Shilling", flag: "KE" },
    KGS: { country: "Kyrgyzstan", name: "Som", flag: "KG" },
    KHR: { country: "Cambodia", name: "Riel", flag: "KH" },
    KMF: { country: "Comoros", name: "Franc", flag: "KM" },
    KRW: { country: "South Korea", name: "Won", flag: "KR" },
    KWD: { country: "Kuwait", name: "Dinar", flag: "KW" },
    KYD: { country: "Cayman Islands", name: "Dollar", flag: "KY" },
    KZT: { country: "Kazakhstan", name: "Tenge", flag: "KZ" },
    LAK: { country: "Laos", name: "Kip", flag: "LA" },
    LBP: { country: "Lebanon", name: "Pound", flag: "LB" },
    LKR: { country: "Sri Lanka", name: "Rupee", flag: "LK" },
    LRD: { country: "Liberia", name: "Dollar", flag: "LR" },
    LSL: { country: "Lesotho", name: "Loti", flag: "LS" },
    LYD: { country: "Libya", name: "Dinar", flag: "LY" },
    MAD: { country: "Morocco", name: "Dirham", flag: "MA" },
    MDL: { country: "Moldova", name: "Leu", flag: "MD" },
    MGA: { country: "Madagascar", name: "Ariary", flag: "MG" },
    MKD: { country: "Macedonia", name: "Denar", flag: "MK" },
    MMK: { country: "Myanmar", name: "Kyat", flag: "MM" },
    MNT: { country: "Mongolia", name: "Tugrik", flag: "MN" },
    MOP: { country: "Macau", name: "Pataca", flag: "MO" },
    MRU: { country: "Mauritania", name: "Ouguiya", flag: "MR" },
    MUR: { country: "Mauritius", name: "Rupee", flag: "MU" },
    MVR: { country: "Maldives", name: "Rufiyaa", flag: "MV" },
    MWK: { country: "Malawi", name: "Kwacha", flag: "MW" },
    MXN: { country: "Mexico", name: "Peso", flag: "MX" },
    MYR: { country: "Malaysia", name: "Ringgit", flag: "MY" },
    MZN: { country: "Mozambique", name: "Metical", flag: "MZ" },
    NAD: { country: "Namibia", name: "Dollar", flag: "NA" },
    NGN: { country: "Nigeria", name: "Naira", flag: "NG" },
    NIO: { country: "Nicaragua", name: "Cordoba", flag: "NI" },
    NOK: { country: "Norway", name: "Krone", flag: "NO" },
    NPR: { country: "Nepal", name: "Rupee", flag: "NP" },
    NZD: { country: "New Zealand", name: "Dollar", flag: "NZ" },
    OMR: { country: "Oman", name: "Rial", flag: "OM" },
    PAB: { country: "Panama", name: "Balboa", flag: "PA" },
    PEN: { country: "Peru", name: "Sol", flag: "PE" },
    PGK: { country: "Papua New Guinea", name: "Kina", flag: "PG" },
    PHP: { country: "Philippines", name: "Peso", flag: "PH" },
    PKR: { country: "Pakistan", name: "Rupee", flag: "PK" },
    PLN: { country: "Poland", name: "Zloty", flag: "PL" },
    PYG: { country: "Paraguay", name: "Guarani", flag: "PY" },
    QAR: { country: "Qatar", name: "Riyal", flag: "QA" },
    RON: { country: "Romania", name: "Leu", flag: "RO" },
    RSD: { country: "Serbia", name: "Dinar", flag: "RS" },
    RUB: { country: "Russia", name: "Ruble", flag: "RU" },
    RWF: { country: "Rwanda", name: "Franc", flag: "RW" },
    SAR: { country: "Saudi Arabia", name: "Riyal", flag: "SA" },
    SBD: { country: "Solomon Islands", name: "Dollar", flag: "SB" },
    SCR: { country: "Seychelles", name: "Rupee", flag: "SC" },
    SDG: { country: "Sudan", name: "Pound", flag: "SD" },
    SEK: { country: "Sweden", name: "Krona", flag: "SE" },
    SGD: { country: "Singapore", name: "Dollar", flag: "SG" },
    SLL: { country: "Sierra Leone", name: "Leone", flag: "SL" },
    SOS: { country: "Somalia", name: "Shilling", flag: "SO" },
    SRD: { country: "Suriname", name: "Dollar", flag: "SR" },
    STN: { country: "Sao Tome", name: "Dobra", flag: "ST" },
    SVC: { country: "El Salvador", name: "Colon", flag: "SV" },
    SYP: { country: "Syria", name: "Pound", flag: "SY" },
    SZL: { country: "Swaziland", name: "Lilangeni", flag: "SZ" },
    THB: { country: "Thailand", name: "Baht", flag: "TH" },
    TJS: { country: "Tajikistan", name: "Somoni", flag: "TJ" },
    TMT: { country: "Turkmenistan", name: "Manat", flag: "TM" },
    TND: { country: "Tunisia", name: "Dinar", flag: "TN" },
    TOP: { country: "Tonga", name: "Pa'anga", flag: "TO" },
    TRY: { country: "Turkey", name: "Lira", flag: "TR" },
    TTD: { country: "Trinidad", name: "Dollar", flag: "TT" },
    TWD: { country: "Taiwan", name: "Dollar", flag: "TW" },
    TZS: { country: "Tanzania", name: "Shilling", flag: "TZ" },
    UAH: { country: "Ukraine", name: "Hryvnia", flag: "UA" },
    UGX: { country: "Uganda", name: "Shilling", flag: "UG" },
    USD: { country: "United States", name: "Dollar", flag: "US" },
    UYU: { country: "Uruguay", name: "Peso", flag: "UY" },
    UZS: { country: "Uzbekistan", name: "Som", flag: "UZ" },
    VES: { country: "Venezuela", name: "Bolivar", flag: "VE" },
    VND: { country: "Vietnam", name: "Dong", flag: "VN" },
    VUV: { country: "Vanuatu", name: "Vatu", flag: "VU" },
    WST: { country: "Samoa", name: "Tala", flag: "WS" },
    XAF: { country: "Central Africa", name: "Franc", flag: "CF" },
    XCD: { country: "East Caribbean", name: "Dollar", flag: "VC" },
    XOF: { country: "West Africa", name: "Franc", flag: "SN" },
    XPF: { country: "French Polynesia", name: "Franc", flag: "PF" },
    YER: { country: "Yemen", name: "Rial", flag: "YE" },
    ZAR: { country: "South Africa", name: "Rand", flag: "ZA" },
    ZMW: { country: "Zambia", name: "Kwacha", flag: "ZM" },
    ZWL: { country: "Zimbabwe", name: "Dollar", flag: "ZW" },
};

export const currencyOptions = Object.keys(countryData).map((code) => ({
  value: code,
  label: `${code} - ${countryData[code].name}`,
}));